version: '2'
services:
  nest:
    env_file:
      - .env.example
    build: .
    container_name: nest-vocabMinder
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    container_name: nest-db
    env_file:
      - .env.example
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
