name: Node.js CI/CD with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Build and Test
        run: docker-compose exec nest-vocabMinder npm run test:e2e
      - name: Clean Up
        run: docker-compose down
